#Setting artifacts root directory and all the necessary directories
artifacts_root: artifacts

#Data ingestion repositories
data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/samaTech-sys/Rising-Village-Prediction-Model/raw/main/interview_dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

#Data Validation repositories
data_validation: 
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/interview_dataset.csv
  STATUS_FILE: artifacts/data_validation/status.txt

#Data processing Repositories 
data_processing:
  root_dir: artifacts/data_processing
  selected_data_file: artifacts/data_processing/selected_features.csv
  validation_report: artifacts/data_validation/selected_features_validation_report.txt

#Data Transformation repositories
data_transformation: 
  root_dir: artifacts/data_transformation
  processed_data_file: artifacts/data_transformation/processed_df.csv

#Data Splitting repositories
data_splitting: 
  root_dir: artifacts/data_splitting
  train_set_path: artifacts/data_splitting/train_set.csv
  test_set_path: artifacts/data_splitting/train_set.csv